@MessageBroker_HostAddress = http://localhost:5254

// List topics
GET {{MessageBroker_HostAddress}}/api/topics/
Accept: application/json

###

// Create topic
POST {{MessageBroker_HostAddress}}/api/topics/
Accept: application/json
Content-Type: application/json

{
    
    "name": "news_feed"
} 

###

// publish message
POST {{MessageBroker_HostAddress}}/api/topics/6/messages
Accept: application/json
Content-Type: application/json

{
   "topicMessage": "new message"
} 

###

// Create subscription
POST {{MessageBroker_HostAddress}}/api/topics/6/subscriptions
Accept: application/json
Content-Type: application/json

{
   "name": "console app"
}

###

// Get subscriber messages
GET {{MessageBroker_HostAddress}}/api/subscriptions/1/messages
Accept: application/json

###

// Acknowledge subscriber messages
POST {{MessageBroker_HostAddress}}/api/subscriptions/1/messages
Accept: application/json
Content-Type: application/json

[10, 11, 12]
