@MessageBroker_HostAddress = http://localhost:5254

// List topics
GET {{MessageBroker_HostAddress}}/api/topics/
Accept: application/json

###

// Create topic
POST {{MessageBroker_HostAddress}}/api/topics/
Accept: application/json
Content-Type: application/json

{
    
    "name": "topic_3"
} 

###

// publish message
POST {{MessageBroker_HostAddress}}/api/topics/1/messages
Accept: application/json
Content-Type: application/json

{
   "topicMessage": "MESSAGE FOR TOPIC 1"
} 

###

// Create subscription
POST {{MessageBroker_HostAddress}}/api/topics/1/subscriptions
Accept: application/json
Content-Type: application/json

{
   "name": "warehouse"
}

###

// Get subscriber messages
GET {{MessageBroker_HostAddress}}/api/subscriptions/1/messages
Accept: application/json

###

// Acknowledge subscriber messages
POST {{MessageBroker_HostAddress}}/api/subscriptions/1/messages
Accept: application/json
Content-Type: application/json

[10, 11, 12]
