@MessageBroker_HostAddress = http://localhost:5254

GET {{MessageBroker_HostAddress}}/api/topics/
Accept: application/json

###

POST {{MessageBroker_HostAddress}}/api/topics/
Accept: application/json
Content-Type: application/json

{
    
    "name": "topic_3"
} 

###

POST {{MessageBroker_HostAddress}}/api/topics/13/messages
Accept: application/json
Content-Type: application/json

{
   "topicMessage": "the body of message"
} 
